version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev
    environment:
      KC_DB: dev-file
      KC_HTTP_RELATIVE_PATH: /
      KC_HOSTNAME_ADMIN: localhost
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
